// BASIC TRY CATCH BLOCK

// try {
//     console.log(a + b)
// } catch (error) {
//     console.log("The code errored out")
// }

// THROW KEYWORD

// throw new ReferenceError();

// try {
//     console.log(a + b);
// } catch (err) {
//     console.log(err);
//     console.log("There was an error");
//     console.log("The error was saved in the error log");
// }

// console.log("My code does not stop");

// try {
//     throw new ReferenceError();
// } catch (err) {
//     console.log(err);
//     console.log("There was a reference error");
// }

// console.log("My code does not stop");